name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python wine_quality_model.py

          echo "## Model metrics" > report.md
          dvc results diff --show-md master > report.md

          echo "## Confusion Matrix" >> report.md
          cml-publish confusion_matrix.png --md >> report.md

          cml-send-comment report.md
